### ISSUE TITLE
Date of Birth Property Missing.

### ISSUE THREAD

**Issue by Hey-Deepak** [stevdza-san/OneTapCompose#12]
**What is the Issue**
The user is not able to get a DOB using this solution.

**What needs to be done?**
We need to add new params i.e. **val dateOfBirth**

**Why this is important?**
In most of apps, we want to know the user's age and according to that, we need to perform certain actions. very important property.

**Comment by stevdza-san** [comment]
That property cannot be obtained directly from Google JWT, instead you need a special permission to access that information.

**Comment by Hey-Deepak** [comment]
Then this is a big problem for this library.
How we can fix it?

**Comment by stevdza-san** [comment]
I'm not really sure about that. I haven't given a thought about that specific info.

**Comment by Hey-Deepak** [comment]
It is important for a reason.
Let me give you some perspective.

DOB helps us to identify
1. when we can wish to someone?
2. Age restriction
3. Today age
4. Feature access according to age limit
Etc.

Otherwise, I need to moveon from this library which I don't want.
Also, I recommend about this library to my friends.
I find it useful and can be used my many people
So are you adding that property?
Please. 🙏🙏🙏


Deepak Choudhary
(Android Engineer)

**Comment by stevdza-san** [comment]
Yes, those are good use-cases. But I'm not really sure that One-Tap API will allow that information through the tokenId. That's the main problem. If you ask me, it's not a problem, but I don't see a solution, because my library depends on One-Tap API. :)

Also there are quite a few popular apps that request that info manually from a user, immediately after a successful sign in, without any library.
